#!/bin/bash

EXPECTED_ARGS=1
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: updatelogs YYYY-MM-DD"
  exit $E_BADARGS
fi

mkdir -p logs/$1

s3cmd sync s3://jeffverkoeyen/logs/$1- logs/$1/

cat logs/$1/* > logs/$1.log
sort -k 3 -n logs/$1.log > logs/$1.sorted.log

cat logs/$1.sorted.log | perl -wlne 'print "$2 - - $1 $3 $4 $5" if /.+? .+? (\[.+?\]) (.+?) .+? .+? .+? .+? (".+?") (.+?) .+? ([0-9]+)/;' > logs/$1.log
egrep -v "( /soap)|( /\?acl)|( /logs)|( /\?prefix)" logs/$1.log > logs/$1.pruned.log
rm logs/$1.sorted.log
mv logs/$1.pruned.log logs/$1.log

mkdir stats
webalizer -o stats logs/$1.log
