#!/bin/bash

DATE=`eval date +%Y-%m-%d`

mkdir -p logs/$DATE

s3cmd sync s3://jeffverkoeyen/logs/$DATE- logs/$DATE/

cat logs/$DATE/* > logs/$DATE.log
sort -k 3 -n logs/$DATE.log > logs/$DATE.sorted.log

cat logs/$DATE.sorted.log | perl -wlne 'print "$2 - - $1 $3 $4 $5" if /.+? .+? (\[.+?\]) (.+?) .+? .+? .+? .+? (".+?") (.+?) .+? ([0-9]+)/;' > logs/$DATE.log
egrep -v "( /soap)|( /\?acl)|( /logs)|( /\?prefix)" logs/$DATE.log > logs/$DATE.pruned.log
rm logs/$DATE.sorted.log
mv logs/$DATE.pruned.log logs/$DATE.log

mkdir stats
webalizer -o stats logs/$DATE.log
